### ISSUE TITLE
Ability to process file passed in by slice instead of by filepath

### ISSUE THREAD

**Issue by val-ms** [royaltm/rust-delharc#3]
It would be nice to have an additional interface to parse a file from a `&[u8]` slice. 

Something along these lines:
```rust
pub fn parse_file_from_bytes(data: &[u8], file_name: &str) -> io::Result<LhaDecodeReader<File>> {
  Ok(LhaDecodeReader::from_bytes(data, file_name)?)
}
```

My example interface passes in the file name (basename) as well, in case you want it for error messages or whatever.  Maybe not needed?

**Comment by royaltm** [comment]
I don't think this is needed. The LhaDecodeReader can take any struct that implemente the `std::io::Reader` trait.

You should be perfectly able to do:

```
let mut slice: &[u8] = get_the_slice_from_somewhere();
let decoder = LhaDecodeReader::new(slice)?;
```
fortunately `&[u8]` also implements io::Reader trait.
https://doc.rust-lang.org/std/io/trait.Read.html#impl-Read-for-%26%5Bu8%5D

you can also use `Cursor<Vec<u8>>` if you want to provide a `Vec<u8>` instead of a slice:

https://doc.rust-lang.org/std/io/trait.Read.html#impl-Read-for-Cursor%3CT%3E
https://doc.rust-lang.org/std/io/struct.Cursor.html

Welcome to Rust traits.

**Comment by royaltm** [comment]
I pushed a little example, so you can see how to go about it:

https://github.com/royaltm/rust-delharc/blob/master/examples/extract.rs

**Comment by val-ms** [comment]
Thanks so much @royaltm I didn't realize.
