### ISSUE TITLE
Errors building crate - missing tessts

### ISSUE THREAD

**Issue by opoplawski** [royaltm/rust-delharc#9]
Trying to build rust-delharc as a Fedora package which uses the crate source I get:
```
error: couldn't read tests/lha_x68k_213.rs: No such file or directory (os error 2)

error: couldn't read tests/unlha32.rs: No such file or directory (os error 2)

error: couldn't read examples/extract.rs: No such file or directory (os error 2)

error: could not compile `delharc` (test "unlha32") due to 1 previous error
```
Looks like there are some missing files in the crate.

**Comment by royaltm** [comment]
What exactly are you doing?

Tests and examples are not included in the rust crate, because they are just too large in comparison to the library itself.

If you want to run tests or examples, clone this github repository.

Otherwise please contact Fedora package maintainer. I'm the author of this rust library and I have nothing to do with Fedora.
